クールタイム画面の実装
lit-kansai/dj-system-ios pull request #62
Opened 2023-05-20 10:43 UTC by silli-3072

## issue番号

resolve #31 

## やったこと

* 曲リクエスト後のクールタイムを表示する画面の実装

## 補足(あれば)

## TODO
- [ ] Reviewersを設定しました
- [ ] Assigneesを設定しました
- [ ] issue番号を記載しました

2023-05-20 10:57 UTC, silli-3072 commented
@txxxxc 
現状、タイマー機能の実装がしてあります。いくつか分かっていないことがあります！

- `var time = Date().timeIntervalSince1970`でtimeの初期値を設定していること

UNIX時間の理解はできたのですが、cooltimeでこれを使う理由がわからなくて300秒で良くないか！！？ってなってます。

- 1秒間隔でCooltimeServiceから残り時間を取得し、更新する

ToDoの部分なのですが、ここの部分が実装ベースまで落とし込んで理解できてないです。

見当違いな実装だったり、質問してたらごめんなさい！改めて教えていただけると嬉しいです！

2023-05-22 10:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        }
ここらへんの実装、[CooltimeService](https://github.com/lit-kansai/dj-system-ios/blob/main/DJSystemiOS/Features/Room/Service/CooltimeService.swift)に実装済みなので、それを使ってください！

2023-05-22 10:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +    @objc func down(timer: Timer) {
関数名、countdownとかのほうが詳細で分かりやすいと思います！いかがでしょうか...?
あと、引数にtimerは受け取らないようにして、ViewController内のcooltimeTimerを参照する感じのほうが自然だと思います！

2023-05-22 10:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +    var time = Date().timeIntervalSince1970
timeはcooltimeSerivceの内部で管理しているので、ここで管理する必要ないと思います！

2023-05-22 10:43 UTC, txxxxc commented
>UNIX時間の理解はできたのですが、cooltimeでこれを使う理由がわからなくて300秒で良くないか！！？ってなってます。

厳密に言うと、クールタイムは`曲をリクエストした時刻から5分間待つ`という仕様なので、Unix時間を使って現在の時刻とUserDefaultsに保存したUnix時間を比較するような形で管理したいです。
300秒とかでやってしまうと、該当するViewControllerを開いている間しかカウントダウンが更新されず、本来の新たにリクエストできるようになる時間と不整合が起きるので運用が難しいって感じです！！


>1秒間隔でCooltimeServiceから残り時間を取得し、更新する
ToDoの部分なのですが、ここの部分が実装ベースまで落とし込んで理解できてないです。

一回CooltimeServiceの実装って読んでみた...?
読むとなんとなく理解できると思うので、一回読んで理解してみてほしいです！(ChatGPTとか使うと良さそう)

2023-05-27 04:38 UTC, txxxxc requested changes
コメントしました！全体に関して言うと、varで定義してるやつのうち、letで置き換えられそうなやつは置き換えてください！

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        var text = cooltimeService.formatTime(hours: setTime.0, minutes: setTime.1, seconds: setTime.2)
これこんな感じで書き換えられそう！
```swift
let remainingCooltime = cooltimeService.getRemainingCooltime()
```

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +            var text = cooltimeService.formatTime(hours: setTime.0, minutes: setTime.1, seconds: setTime.2)
これこんな感じで書き換えられそう！
```swift
let remainingCooltime = cooltimeService.getRemainingCooltime()
```

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        if setTime == nil {
setTimeがnilの時は基本的に無いので考えなくて大丈夫！guard letでreturnしてもらう感じで大丈夫です！

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +    var time = Date().timeIntervalSince1970 + 300
timeはローカルに定義するのではなく、UserDefaultsで運用してください！
UserDefaultsに保存したら、CooltimeServiceが勝手に取得してくれるようになっています！

詳しくはこちらを読んでもらえると🙇‍♂️↓
[dj-system-ios/CooltimeService.swift at main · lit-kansai/dj-system-ios](https://github.com/lit-kansai/dj-system-ios/blob/main/DJSystemiOS/Features/Room/Service/CooltimeService.swift)
[dj-system-ios/CooltimeDataSource.swift at main · lit-kansai/dj-system-ios · GitHub](https://github.com/lit-kansai/dj-system-ios/blob/main/DJSystemiOS/Features/Room/DataSource/CooltimeDataSource.swift#L4)

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
>          cooltimeService.saveCooltime(unixTime: time)
ここのsaveCooltime必要ないかも...!

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> + */
これ一旦消しておいてもらえると助かる！

2023-05-27 04:38 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        if text == "00:00" {
ここ、cooltimeService.hasExpiredで書き換えたい！
https://github.com/lit-kansai/dj-system-ios/blob/1cec88554c19a197d6b486de540087b14a6fc4c0/DJSystemiOS/Features/Room/Service/CooltimeService.swift#L47-L52

2023-06-06 05:15 UTC, txxxxc requested changes
レビューしました！修正よろ！！

2023-06-06 05:15 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        cooltimeService.saveCooltime(unixTime: Date().timeIntervalSince1970 + 30)
ここ、動作確認時だけ使ってほしいです！コミットする時は消してください！！

2023-06-06 05:15 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        }
ここcooltimeService.hasExpiredを使ったほうが自然なので、、書き換えてほしいです！

2023-06-06 05:15 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +    func timer() {
timerだけだと抽象的なので、動詞をつけてあげてください！(例：startTimerなど)

2023-06-06 05:15 UTC, txxxxc commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        }
ここ、guard letで書いたほうが見やすくなるので書き換えてほしいです！

2023-06-06 07:00 UTC, txxxxc reviewed
コメントした！！

2023-06-06 07:00 UTC, txxxxc reviewed
コメントした！！

2023-06-06 07:57 UTC, silli-3072 commented on DJSystemiOS/Pages/CooltimePage/CooltimeViewController.swift
> +        if cooltimeService.hasExpired == false {
`false`とか指定しなくていいってことですか！！？
それで実装してプッシュしました！

2023-06-07 05:10 UTC, txxxxc approved these changes
良い！！

2023-06-07 05:39 UTC, merged